sudo: required
cache:
  directories: $HOME/.m2
os: linux
dist: xenial
language: java
jdk: openjdk11
before_install:
  - sudo /etc/init.d/postgresql stop
  - ./checkout_FrameworkBenchmarks.sh
  - ./build_FrameworkBenchmarks.sh
