sudo: required
cache:
  directories: $HOME/.m2
os: linux
dist: xenial
language: java
jdk: openjdk11
before_install: 
  - sudo echo "" >> /etc/hosts
  - sudo echo "127.0.0.1 tfb-datbase" >> /etc/hosts
  - ./checkout_FrameworkBenchmarks.sh
  - ./build_FrameworkBenchmarks.sh
