trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    ./checkout_FrameworkBenchmarks.sh
  displayName: 'Checkout FramworkBenchmarks'

- task: Maven@3
  displayName: 'Build FrameworkBenchmarks'
  inputs:
    mavenPomFile: 'FrameworkBenchmarks/frameworks/Java/officefloor/src/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    publishJUnitResults: false
    goals: 'install'

- task: Maven@3
  displayName: 'Test'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'install'
