name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Tests
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Checkout Framework
      run: ./checkout_FrameworkBenchmarks.sh
    
    - name: Build Framework
      run: ./build_FrameworkBenchmarks.sh
        
    - name: Test
      run: mvn -B install
